name: upgrade
description: AI-powered personalized study planner
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.2.1
  http: ^1.2.0


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  fl_chart: ^0.66.0
  intl: ^0.19.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
